server:
  port: 7001

spring:
  application:
    name: ORDER-SERVICE

# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: true
    fetch-registry: true