server:
  port: 7001

spring:
  application:
    name: order-service

# Eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8088/eureka/}
    register-with-eureka: true
    fetch-registry: true